qa:
  server:
    port: 8080
  database:
    dns: "host=localhost user=yourUserName password=yourPassword dbname=YourDb port=5432 sslmode=disable TimeZone=Asia/Shanghai search_path=public"
  vault:
    addr: "http://127.0.0.1:8200"
    initialRootToken: "xxxx"
    unsealKeys:
      - "xxxx"
      - "xxxx"
      - "xxxx"
      - "xxxx"
      - "xxxx"
  email:
    host: "smtp.example.com"
    port: 587
    user: "yourmail0@example.com"
  redis:
    addr: "localhost:6379"
    password: "xxxx"
    db: 0
  log:
    level: 1 # 0: Debug, 1: Info, 2: Warn, 3: Error, 4: Fatal, 5: Panic, 6: NoLog, 7:Disabled, -1: Trace

prod:
