services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200" # API için
    volumes:
      - ./vault-config:/vault/config # Konfigürasyon dosyası için
      - ./vault-data:/vault/data     # Kalıcı veri depolama için
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: |
        {
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          },
          "storage": {
            "file": {
              "path": "/vault/data"
            }
          },
          "api_addr": "http://localhost:8200",
          "cluster_addr": "http://localhost:8201"
        }
    command: server